### ISSUE TITLE
Migrate to Improvmx

### ISSUE THREAD

**Issue by Matthijsy** [csvalpha/amber-api#156]
We would like to migrate our mailsystem to Improvmx, this is a forwarding service for mail that works good. 

This are the steps that I would like to follow
- [x] Implement synchronization from Amber to Improvmx (#157)
- [x] Get permission from the board to spend 90 dollars a year
- [x] Get the 'verwerkersovereenkomst' from Improvmx
- [x] Update the privacy statement and inform the members (in progress)
- [x] Implement 'moderated' lists
- [x] Determine what to do with 'semi-moderated' lists (will be open lists for now)
- [x] Implement SMTP (optional, can also be done manual)
- [x] Go Live

Would like what you all think about this

**Comment by Matthijsy** [comment]
Done!! Only some cleanup left, but will close this issue for now
